photos/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('photos.views',
    url(r'^$', 'toppage', name='photo_toppage'),
    url(r'^(?P<photo_id>[0-9]+)/$', 'single_photo', name='single_photo'),
    url(r'^create/$', 'edit_photo'),
    url(r'^(?P<photo_id>[0-9]+)/like/$', 'like_photo', name='like_photo'),
    url(r'^(?P<photo_id>[0-9]+)/edit/$', 'edit_photo'),
    url(r'^(?P<photo_id>[0-9]+)/comment/$', 'single_photo', name='edit_photo_comment'),
)

pystagram/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

from photos import urls as photo_urls
from profiles import urls as profile_urls

from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', 'profiles.views.timeline', name='timeline'),
    url(r'^photos/', include(photo_urls)),
    url(r'^profiles/', include(profile_urls)),

    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name="login_url"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/login/'}, name="logout_url"),
    url(r'^signup/$', 'profiles.views.signup'),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'profiles.views.my_handler404'

photos/models.py
# coding: utf-8

from django.conf import settings
from django.db import models
from django.db.models import Q

class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    image_file = models.ImageField(upload_to='%Y/%m/%d/')
    is_active = models.BooleanField(default=True)
    description = models.TextField(null=True)
    tags = models.ManyToManyField('Tag')
    # likes = models.ManyToManyField(
    #     settings.AUTH_USER_MODEL, related_name='like_user_set')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=True, auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-id']
        get_latest_by = 'updated_at'

    def __unicode__(self):
        return u"{0} - '{1}'".format(self.id, self.user)

    def is_liked(self, user):
        if isinstance(user, basestring):
            _q = Q(user_username=user)
        elif isinstance(user, self.user.__class__):
            _q = Q(user=user)
        else:
            return False

        return self.like_set.filter(_q & Q(is_active=True)).exists()

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ForeignKey(Photo)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=True, auto_now=True)

    def __unicode__(self):
        return u"{0} 'photo : {1}'".format(self.id, self.photo.id)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ForeignKey(Photo)
    content = models.TextField(null=False, max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=True, auto_now=True)

    def __unicode__(self):
        return u"{0} 'photo : {1}'".format(self.id, self.photo.id)

class Tag(models.Model):
    name = models.CharField(max_length=80)

    def __unicode__(self):
        return u"{0}".format(self.name)

photos/forms.py
# coding: utf-8

from django import forms
from .models import Photo, Comment

CHOICES = (
    ('a', 'A item',),
    ('b', 'B item',),
    ('c', 'C item',),
    ('d', 'D item',),
)

class PhotoForm(forms.Form):
    image_file = forms.ImageField()
    description = forms.CharField(widget=forms.Textarea)

class PhotoModelForm(forms.ModelForm):
    tags = forms.CharField(required=False, max_length=200)
    class Meta:
        model = Photo
        fields = ('image_file', 'description',)

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

photos/views.py
# coding: utf-8

import base64

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.files.uploadedfile import SimpleUploadedFile

from photos.models import Photo, Comment, Tag, Like
from photos.forms import PhotoModelForm, CommentModelForm

def toppage(request):
    return HttpResponse('hello')

@login_required
def like_photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)

    like, _created = Like.objects.get_or_create(
        user=request.user, photo=photo,
        defaults={
            'user':request.user,
            'photo':photo,
        })

    if not _created:
        like.is_active = not like.is_active
        like.save()

    return HttpResponseRedirect(
        reverse('single_photo', kwargs={'photo_id':photo.id})
    )


def single_photo(request, photo_id):
    if int(photo_id) == 0:
        return HttpResponseRedirect(reverse('photo_toppage'))

    photo = get_object_or_404(Photo, pk=photo_id)

    if request.user.is_authenticated():
        is_liked = photo.is_liked(request.user)
    else:
        is_liked = False

    if request.method == "GET":
        comment_form = CommentModelForm()
    elif request.method == "POST":
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('login_url'))

        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            _comment = comment_form.save(commit=False)
            _comment.user = request.user
            _comment.photo = photo
            _comment.save()

            return HttpResponseRedirect(request.path)

    return render(
        request,
        'single_photo.html',
        {
            'photo': photo,
            'comment_form': comment_form,
            'is_liked': is_liked,
        }
    )


def get_base64_image(data):
    if data.count(';base64,') == 0:
        return None

    _format, _content = data.split(';base64,')
    return base64.b64decode(_content)


@login_required
def edit_photo(request, photo_id=None):
    if request.method == 'GET':
        form = PhotoModelForm()
    elif request.method == 'POST':
        if request.POST.get('filtered_image_file'):
            _file = get_base64_image(
                request.POST.get('filtered_image_file', '')
            )
            _filedata = {
                'image_file': SimpleUploadedFile(
                    request.FILES['image_file'].name.split('/')[-1], _file
                )
            }
        else:
            _filedata = request.FILES

        form = PhotoModelForm(request.POST, _filedata)

        if form.is_valid():
            _photo = form.save(commit=False)
            _photo.user = request.user
            _photo.save()

            for _tagname in request.POST.get('tags', '').split(','):
                _tagname = _tagname.strip()
                _tag, _created = Tag.objects.get_or_create(
                    name=_tagname, defaults={'name':_tagname}
                )
                _photo.tags.add(_tag)

            return HttpResponseRedirect('/photos/{0}/'.format(_photo.id))

    return render(request, 'edit_photo.html', {
            'form': form,
        })

templates/photos/edit_photo.html
{% load staticfiles %}<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <title>사진 보기</title>
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.vintage.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vintage.presets.js' %}"></script>

    <script type="text/javascript">
    $(window).load(function(e) {
        $('#id_image_file').change(function(e) {
            var reader = new FileReader();

            $('#preview_photo').hide();

            reader.onerror = function(e) { console.log(e); }
            reader.onloadend = function(e) {
                if ( (/^data\:image\/(jpeg|png);base64/i).test(e.target.result) ) {
                    $('#preview_photo').attr('src', e.target.result).show();
                }
                else {
                    if ( e.total == 0 || e.loaded == 0 ) {
                        alert('파일을 가져오지 못 했습니다.');
                    }
                    else {
                        alert('허용된 사진 파일이 아닙니다.');
                    }
                    $('#id_image_file').val('');
                }
            }
            reader.readAsDataURL(this.files[0]);
        });

        $('#image_filter_buttons > button').click(function(e) {
            switch ( $(this).val() ) {
                case 'reset':
                    if ( $('#preview_photo').data('vintageJS') ) {
                      $('#preview_photo').data('vintageJS')[$(this).val()]();
                    }
                    break;

                case 'vintage':
                case 'sepia':
                case 'greenish':
                case 'reddish':
                    if ( $('#preview_photo').data('vintageJS') ) {
                        $('#preview_photo').data('vintageJS')
                            .vintage(vintagePresets[$(this).val()]);
                    }
                    else {
                        $('#preview_photo').vintage(
                            {
                                onError: function() { console.log('vintage error'); },
                                onStart: function() { console.log('filtering start'); },
                                onStop: function() { console.log('filtering stop'); },
                                mime: 'image/png'
                            },
                            vintagePresets[$(this).val()]
                        );
                    }
                    break;
            }
        });

        $('#edit_photo_form').submit(function(e) {
            $('#filtered_image_file').val($('#preview_photo').attr('src'));
        });

    });
    </script>
</head>

<body>

{% if form.is_multipart %}
<form method="POST" id="edit_photo_form" action="{{request.path}}" enctype="multipart/form-data">
{% else %}
<form method="POST" id="edit_photo_form" action="{{request.path}}">
{% endif %}
{% csrf_token %}
<input type="hidden" id="filtered_image_file" name="filtered_image_file" value="" />
{{form.as_p}}

  <div id="image_filter_buttons">
    <button type="button" value="vintage">Vintage</button>
    <button type="button" value="sepia">Sephia</button>
    <button type="button" value="greenish">Greenish</button>
    <button type="button" value="reddish">Reddish</button>
    <button type="button" value="reset">원래대로</button>
  </div>

  <div>
    <img id="preview_photo" src="" />
  </div>

<input type="submit" value="저장" />
</form>


</body>

</html>

templates/photos/single_photo.html
{% load staticfiles %}
<html>

<head>
    <title>사진 보기</title>
</head>

<body>
{% if request.user.is_authenticated %}
<p>로그인한 이용자</p>
{% else %}
<p>로그인 안 한 이용자</p>
{% endif %}

    <ul>
        <li>{{photo.id}}</li>
        <li><img src="{{photo.image_file.url}}" /></li>
        <li>{{photo.description}}</li>
        {% if photo.tags.count %}
        <li>{% for tag in photo.tags.all %}
            <span>{{tag}}</span>
        {% endfor %}</li>{% endif %}
        <li><a href="{% url 'like_photo' photo.id %}">{% if is_liked %}
        좋아요 취소
        {% else %}
        좋아요
        {% endif %}</a></li>
        {% if photo.likes.count %}
        <li>{{photo.likes.count}}명이 좋아합니다.<ul>
            {% for like in photo.likes.all %}
            <li><a href="{% url 'profile_page' like.username %}">{{like.username}}</a></li>
            {% endfor %}
        </ul></li>
        {% endif %}
    </ul>

    {% if photo.comment_set.count %}
    <ul>
        {% for comment in photo.comment_set.all %}
        <li><span>{{comment.user}}</span> : {{comment.content}} ({{comment.updated_at}})</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form method="POST" action="{% url 'edit_photo_comment' photo.id %}">
        {% csrf_token %}

        {{comment_form.as_p}}

        <p><input type="submit" value="댓글 달기" /></p>
    </form>
</body>
</html>

templates/photos/timeline.html
{% load social_activity %}

<h2>{{request.user}}의 timeline</h2>
{% for photo in photos %}
<div>
    <p>{{photo.id}} : {{photo.user}}</p>
    <p><a href="{% url 'single_photo' photo.id %}"><img src="{{photo.image_file.url}}"/></a></p>
    <p><a href="{% url 'like_photo' photo.id %}">{% if photo|is_liked:request.user %}
        좋아요 취소
    {% else %}
    좋아요
    {% endif %}</a></p>
</div>
{% endfor %}